Algoritmo "mais_velho"



Var

   N, i, posicao, a: inteiro
   nome: vetor [0..9] de caractere
   idade: vetor [0..9] de inteiro

Inicio

   escreva ("Quantas pessoas voce vai digitar? ")
   leia (N)

   a <- idade[0]

   para i de 0 ate N-1 faca

      escreval ("Dados da ", i+1,"a pessoa: ")
      escreva ("Nome: ")
      leia (nome[i])
      escreva ("Idade: ")
      leia (idade[i])

      se idade [i] > a entao
         a <- idade[i]
         posicao <- i
      fimse

   fimpara
   escreval ("PESSOA MAIS VELHA: ", nome[posicao])

Fimalgoritmo