Algoritmo "exercicio1"

Var

  produto1: caractere
  produto2: caractere
  preco1: real
  preco2: real
  idade: inteiro
  codigo: inteiro
  genero: caractere

Inicio

  produto1 <- "Computador"
  produto2 <- "TV"
  preco1 <- 2100.5
  preco2 <-1830.0
  idade <- 30
  codigo <- 5291
  genero <- "F"
  
  escreval ("Produtos:")
  escreval ("O ", produto1 ," custa R$", preco1:6)
  escreval ("O ", produto2 ," custa R$", preco2:6)
  escreval
  escreval ("Codigo = ", codigo)
  escreval
  escreval ("Dados da pessoa: genero ", genero " e idade" idade)


Fimalgoritmo